-- ==============================================
-- Energy Monitoring API - Database Migration
-- Versão: 1.0
-- Autor: RM560139
-- Data: 03/12/2024
-- ==============================================

-- Criar tabela de usuários
CREATE TABLE USERS (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME NVARCHAR2(50) NOT NULL,
    EMAIL NVARCHAR2(100) NOT NULL,
    PASSWORD_HASH NVARCHAR2(255) NOT NULL,
    ROLE NVARCHAR2(20) DEFAULT 'User' NOT NULL,
    CREATED_AT TIMESTAMP(7) NOT NULL
);

-- Criar índices únicos para USERS
CREATE UNIQUE INDEX IX_USERS_USERNAME ON USERS(USERNAME);
CREATE UNIQUE INDEX IX_USERS_EMAIL ON USERS(EMAIL);

-- Criar tabela de leituras de energia
CREATE TABLE ENERGY_READINGS (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID NVARCHAR2(50) NOT NULL,
    LOCATION NVARCHAR2(200) NOT NULL,
    ENERGY_CONSUMPTION NUMBER(18,2) NOT NULL,
    POWER_DEMAND NUMBER(18,2) NOT NULL,
    READING_DATE TIMESTAMP(7) NOT NULL,
    ENERGY_SOURCE NVARCHAR2(50) DEFAULT 'Grid' NOT NULL,
    COST_PER_KWH NUMBER(18,2) NOT NULL,
    TOTAL_COST NUMBER(18,2) NOT NULL
);

-- Criar índices para ENERGY_READINGS
CREATE INDEX IX_ENERGY_READINGS_DEVICE_ID ON ENERGY_READINGS(DEVICE_ID);
CREATE INDEX IX_ENERGY_READINGS_READING_DATE ON ENERGY_READINGS(READING_DATE);

-- Criar tabela de alertas
CREATE TABLE ALERTS (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID NVARCHAR2(50) NOT NULL,
    ALERT_TYPE NVARCHAR2(100) NOT NULL,
    MESSAGE NVARCHAR2(500) NOT NULL,
    SEVERITY NVARCHAR2(20) DEFAULT 'Medium' NOT NULL,
    CREATED_AT TIMESTAMP(7) NOT NULL,
    IS_RESOLVED NUMBER(1) DEFAULT 0 NOT NULL
);

-- Criar índice para ALERTS
CREATE INDEX IX_ALERTS_DEVICE_ID ON ALERTS(DEVICE_ID);

-- Criar tabela de controle de migrations
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Registrar migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241203_InitialCreate', '8.0.0');

COMMIT;